"""SAGO Error Handling & Recovery Subsystem."""

from __future__ import annotations

from sago.errors.exceptions import (
    AgentDelegationError,
    AgentError,
    AgentExecutionError,
    AgentNotFoundError,
    AgentTimeoutError,
    APIKeyError,
    CacheError,
    ConfigError,
    CycleDetectedError,
    DatabaseError,
    LLMError,
    ModelNotFoundError,
    ProviderNotFoundError,
    RateLimitError,
    RecursionLimitError,
    SagoError,
    SameAgentLimitError,
    SystemError,
    ToolError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolPermissionError,
    ToolTimeoutError,
)
from sago.errors.handler import (
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_BACKOFF,
    DEFAULT_RETRY_DELAY,
    PERMANENT_ERRORS,
    TRANSIENT_ERRORS,
    ErrorContext,
    ErrorHandler,
    ErrorSeverity,
    RecoveryManager,
    RecoveryResult,
    RecoveryStrategy,
    get_error_handler,
    get_recovery_manager,
)

__all__ = [
    "SagoError",
    "ToolError",
    "ToolNotFoundError",
    "ToolExecutionError",
    "ToolTimeoutError",
    "ToolPermissionError",
    "AgentError",
    "AgentNotFoundError",
    "AgentExecutionError",
    "AgentTimeoutError",
    "AgentDelegationError",
    "RecursionLimitError",
    "CycleDetectedError",
    "SameAgentLimitError",
    "LLMError",
    "ProviderNotFoundError",
    "APIKeyError",
    "RateLimitError",
    "ModelNotFoundError",
    "SystemError",
    "DatabaseError",
    "CacheError",
    "ConfigError",
    "ErrorSeverity",
    "RecoveryStrategy",
    "ErrorContext",
    "RecoveryResult",
    "ErrorHandler",
    "RecoveryManager",
    "get_error_handler",
    "get_recovery_manager",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_DELAY",
    "DEFAULT_RETRY_BACKOFF",
    "TRANSIENT_ERRORS",
    "PERMANENT_ERRORS",
]
