"""OpenTelemetry & Prometheus Telemetry Exporters for SAGO.

Converts internal developer trace events into standard OpenTelemetry (OTel) v1
Trace JSON schemas and Prometheus metrics exposition format for enterprise observability.
"""

from __future__ import annotations

import hashlib
import time
from typing import Any

from sago.tracking.dev_tracer import DevTraceEvent, get_dev_tracer


def _generate_id(seed: str, length: int = 16) -> str:
    """Generate deterministic hex ID of specified byte length."""
    h = hashlib.sha256(seed.encode()).hexdigest()
    return h[: length * 2]


class OTelExporter:
    """Exports SAGO developer trace telemetry into OpenTelemetry Trace JSON specification."""

    def __init__(self, service_name: str = "sago-agent", service_version: str = "0.1.6") -> None:
        self.service_name = service_name
        self.service_version = service_version

    def export_traces(self, events: list[DevTraceEvent] | None = None) -> dict[str, Any]:
        """Convert trace events into OTel ResourceSpans payload."""
        if events is None:
            events = get_dev_tracer().get_events()

        trace_id = _generate_id(
            f"sago-session-{events[0].timestamp if events else time.time()}", 16
        )

        spans: list[dict[str, Any]] = []
        for i, ev in enumerate(events):
            span_id = _generate_id(f"{ev.source}:{ev.action}:{ev.timestamp}:{i}", 8)
            start_nano = int(ev.timestamp * 1_000_000_000)
            end_nano = start_nano + int(ev.duration_ms * 1_000_000)

            # Build OTel attributes
            attributes = [
                {"key": "sago.event_type", "value": {"stringValue": ev.event_type.value}},
                {"key": "sago.source", "value": {"stringValue": ev.source}},
                {"key": "sago.status", "value": {"stringValue": ev.status}},
            ]
            if ev.duration_ms > 0:
                attributes.append(
                    {"key": "sago.duration_ms", "value": {"doubleValue": round(ev.duration_ms, 2)}}
                )

            for k, v in ev.data.items():
                if isinstance(v, (int, float)):
                    attributes.append({"key": f"sago.data.{k}", "value": {"doubleValue": float(v)}})
                elif isinstance(v, bool):
                    attributes.append({"key": f"sago.data.{k}", "value": {"boolValue": v}})
                else:
                    attributes.append(
                        {"key": f"sago.data.{k}", "value": {"stringValue": str(v)[:250]}}
                    )

            status_code = 1 if ev.status == "OK" else 2
            span: dict[str, Any] = {
                "traceId": trace_id,
                "spanId": span_id,
                "name": f"{ev.source}::{ev.action}",
                "kind": 1,  # SPAN_KIND_INTERNAL
                "startTimeUnixNano": str(start_nano),
                "endTimeUnixNano": str(end_nano),
                "attributes": attributes,
                "status": {"code": status_code},
            }
            spans.append(span)

        return {
            "resourceSpans": [
                {
                    "resource": {
                        "attributes": [
                            {"key": "service.name", "value": {"stringValue": self.service_name}},
                            {
                                "key": "service.version",
                                "value": {"stringValue": self.service_version},
                            },
                            {
                                "key": "telemetry.sdk.name",
                                "value": {"stringValue": "sago-otel-tracer"},
                            },
                            {"key": "telemetry.sdk.language", "value": {"stringValue": "python"}},
                        ]
                    },
                    "scopeSpans": [
                        {
                            "scope": {
                                "name": "sago.tracking.dev_tracer",
                                "version": self.service_version,
                            },
                            "spans": spans,
                        }
                    ],
                }
            ]
        }


class PrometheusExporter:
    """Exports trace and performance telemetry into Prometheus text exposition format."""

    def __init__(self, namespace: str = "sago") -> None:
        self.namespace = namespace

    def export_metrics(self, events: list[DevTraceEvent] | None = None) -> str:
        """Format metrics into Prometheus exposition text format."""
        if events is None:
            events = get_dev_tracer().get_events()

        lines = [
            f"# Generated by SAGO Prometheus Telemetry Exporter at {time.strftime('%Y-%m-%d %H:%M:%S')}",
            f"# HELP {self.namespace}_events_total Total count of telemetry events recorded",
            f"# TYPE {self.namespace}_events_total counter",
        ]

        event_counts: dict[tuple[str, str, str], int] = {}
        tool_counts: dict[tuple[str, str], int] = {}
        durations: list[float] = []

        for ev in events:
            key = (ev.event_type.value, ev.source, ev.status)
            event_counts[key] = event_counts.get(key, 0) + 1

            if ev.data.get("tool_name"):
                t_key = (str(ev.data["tool_name"]), ev.status)
                tool_counts[t_key] = tool_counts.get(t_key, 0) + 1

            if ev.duration_ms > 0:
                durations.append(ev.duration_ms)

        for (e_type, src, status), count in sorted(event_counts.items()):
            lines.append(
                f'{self.namespace}_events_total{{event_type="{e_type}",source="{src}",status="{status}"}} {count}'
            )

        if tool_counts:
            lines.append("")
            lines.append(
                f"# HELP {self.namespace}_tool_dispatches_total Total tool execution count"
            )
            lines.append(f"# TYPE {self.namespace}_tool_dispatches_total counter")
            for (tool_name, status), count in sorted(tool_counts.items()):
                lines.append(
                    f'{self.namespace}_tool_dispatches_total{{tool="{tool_name}",status="{status}"}} {count}'
                )

        if durations:
            avg_dur = sum(durations) / len(durations)
            max_dur = max(durations)
            lines.append("")
            lines.append(
                f"# HELP {self.namespace}_function_duration_ms Function latency diagnostics in milliseconds"
            )
            lines.append(f"# TYPE {self.namespace}_function_duration_ms gauge")
            lines.append(f'{self.namespace}_function_duration_ms{{stat="avg"}} {avg_dur:.2f}')
            lines.append(f'{self.namespace}_function_duration_ms{{stat="max"}} {max_dur:.2f}')
            lines.append(f'{self.namespace}_function_duration_ms{{stat="count"}} {len(durations)}')

        lines.append("")
        return "\n".join(lines)
